services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventos-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/eventosdb
      SPRING_DATASOURCE_USERNAME: eventos_user
      SPRING_DATASOURCE_PASSWORD: clave_segura
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: valor_super_secreto
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: eventos-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: eventosdb
      POSTGRES_USER: eventos_user
      POSTGRES_PASSWORD: clave_segura
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: